# This is a workflow which display most of lowlighter/metrics features
#
# It is also used to detect broken plugins, so that's why "plugins_errors_fatal" is enabled on most of them,
# but you should set it to no if you're copying steps from this workflow
#
# ‚ö†Ô∏è Following jobs all uses @master branch (unstable branch with unreleased features)

name: Metrics (examples)
on:
  schedule:
    - cron: "0 2-23/4 * * *"
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    if: "github.repository == 'undecidedsource/undecidedsource'"
    steps:
      # ======================================================================================
      # üåá GitHub Skyline 3D calendar

      # GitHub skyline commits calendar
      - name: üåá GitHub Skyline 3D calendar
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@master
        with:
          filename: metrics.plugin.skyline.svg
          token: NOT_NEEDED
          plugin_skyline: yes
          plugin_skyline_year: 2020
          plugin_skyline_frames: 6
          plugin_skyline_quality: 1
          plugins_errors_fatal: ${{ github.repository == 'undecidedsource/undecidedsource' }}
          output_action: pull-request
